# Generated by Django 5.1.7 on 2025-04-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerlike',
            name='value',
            field=models.IntegerField(choices=[(1, 'Like'), (-1, 'Dislike')]),
        ),
        migrations.AlterField(
            model_name='questionlike',
            name='value',
            field=models.IntegerField(choices=[(1, 'Like'), (-1, 'Dislike')]),
        ),
    ]
