# Generated by Django 5.1.7 on 2025-05-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_answerlike_value_alter_questionlike_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='likes_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='likes_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
